/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}




//        JsonNode root = mapper.readTree(new File(TRAIN_PATH));
//        ArrayNode arr = (ArrayNode) root.get("seats");
//        ObjectNode first = (ObjectNode) arr.get(0);
//        first.put("name", "Naya Name");


